#!/usr/bin/env node
import { fileURLToPath } from "node:url";
import { Command } from "commander";

import { detectAgents, pairingAgentsFromProbeResults } from "./agents/detector.js";
import { pairWithCloud } from "./auth/pairing.js";
import { loadConfig, saveConfig } from "./config.js";
import { startBridge } from "./stream/websocket-client.js";
import type { BridgeConfig } from "./types.js";
import { BRIDGE_VERSION } from "./types.js";

export async function runCli(argv = process.argv): Promise<void> {
	const program = new Command();

	program
		.name("agentdeck-bridge")
		.description("AgentDeck local bridge: pair this machine, detect coding agents, and stream local runtime events.")
		.version(BRIDGE_VERSION);

	program
		.command("pair")
		.argument("<pairing-code>", "Pairing code generated by AgentDeck Mission Control.")
		.option("--cloud-url <url>", "AgentDeck cloud URL.", process.env.AGENTDECK_CLOUD_URL ?? "http://localhost:3000")
		.option("--display-name <name>", "Machine display name.")
		.option("--skip-probe", "Pair without probing installed coding agents.")
		.action(async (pairingCode: string, options: { cloudUrl: string; displayName?: string; skipProbe?: boolean }) => {
			const probeResults = options.skipProbe ? [] : await detectAgents();
			const config = await pairWithCloud(pairingCode, {
				agents: pairingAgentsFromProbeResults(probeResults),
				cloudUrl: options.cloudUrl,
				displayName: options.displayName,
			});
			await saveConfig(config);
			console.log(`Paired AgentDeck bridge machine ${config.machineId} with workspace ${config.workspaceId}.`);
		});

	program
		.command("probe")
		.description("Detect installed coding agents and auth state.")
		.option("--json", "Print JSON output.")
		.action(async (options: { json?: boolean }) => {
			const results = await detectAgents();
			if (options.json) {
				console.log(JSON.stringify(results, null, 2));
				return;
			}

			for (const result of results) {
				console.log(`${result.agentKind}: ${result.found ? "found" : "not found"}`);
				if (result.found) {
					console.log(`  command: ${result.command}`);
					console.log(`  version: ${result.version ?? "unknown"}`);
					console.log(`  auth: ${result.authStatus}`);
					console.log(`  capabilities: ${result.capabilities.join(", ")}`);
				}
				for (const warning of result.warnings) {
					console.log(`  warning: ${warning}`);
				}
			}
		});

	program
		.command("start")
		.description("Connect the bridge to a SessionHub and wait for control messages.")
		.argument("[session-id]", "Session id to connect to. Falls back to AGENTDECK_SESSION_ID or config.defaultSessionId.")
		.option("--privacy-mode <mode>", "Override privacy mode: local-only, metadata-only, or full-sync.")
		.action(async (sessionIdArg: string | undefined, options: { privacyMode?: BridgeConfig["privacyMode"] }) => {
			const config = await loadConfig();
			const sessionId = sessionIdArg ?? process.env.AGENTDECK_SESSION_ID ?? config.defaultSessionId;
			if (!sessionId) {
				throw new Error("Missing session id. Run: agentdeck-bridge start <session-id>");
			}

			const runtime = await startBridge(config, {
				privacyMode: options.privacyMode ?? config.privacyMode,
				sessionId,
			});
			console.log(`AgentDeck bridge connected to session ${sessionId}.`);

			const shutdown = () => {
				runtime.close();
				process.exit(0);
			};
			process.once("SIGINT", shutdown);
			process.once("SIGTERM", shutdown);
		});

	await program.parseAsync(argv);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
	runCli().catch((error) => {
		console.error(error instanceof Error ? error.message : String(error));
		process.exit(1);
	});
}
