import type {
	ActiveRun,
	AgentInstallation,
	DecisionReport,
	NavigationItem,
	PolicyRule,
	QueueItem,
	ScheduledJob,
	WorkspaceSummary,
} from "@agentdeck/core";

export const navigationItems: NavigationItem[] = [
	{ id: "mission", label: "Mission" },
	{ id: "sessions", label: "Sessions", count: 12 },
	{ id: "agents", label: "Agents", count: 5 },
	{ id: "queue", label: "Queue", count: 4 },
	{ id: "schedules", label: "Schedules", count: 3 },
	{ id: "reports", label: "Reports" },
	{ id: "policies", label: "Policies" },
	{ id: "settings", label: "Settings" },
];

export const workspaceSummary: WorkspaceSummary = {
	id: "wrk_astx",
	name: "AsthriX",
	repo: "agentdeck",
	branch: "main",
	privacyMode: "metadata-only",
	machineCount: 2,
	costTodayUsd: 8.74,
	pendingApprovals: 2,
};

export const agentInstallations: AgentInstallation[] = [
	{
		id: "agent_claude",
		kind: "claude-code",
		name: "Claude Code",
		command: "claude",
		version: "2.1.8",
		status: "running",
		authStatus: "configured",
		capabilities: ["terminal", "repo-aware", "code-edit", "bash", "mcp"],
		latencyMs: 132,
		lastSeenLabel: "live",
		recommendedFor: "Complex repo changes and broad reasoning",
	},
	{
		id: "agent_codex",
		kind: "codex",
		name: "Codex CLI",
		command: "codex",
		version: "0.42.0",
		status: "waiting",
		authStatus: "configured",
		capabilities: ["terminal", "repo-aware", "code-edit", "bash", "model-switching"],
		latencyMs: 188,
		lastSeenLabel: "2m ago",
		recommendedFor: "Focused implementation and review loops",
	},
	{
		id: "agent_opencode",
		kind: "opencode",
		name: "OpenCode",
		command: "opencode",
		version: "1.3.5",
		status: "passed",
		authStatus: "configured",
		capabilities: ["terminal", "repo-aware", "code-edit", "bash", "acp"],
		latencyMs: 94,
		lastSeenLabel: "8m ago",
		recommendedFor: "Open agent flows and ACP experiments",
	},
	{
		id: "agent_qwen",
		kind: "qwen-code",
		name: "Qwen Code",
		command: "qwen",
		status: "auth-missing",
		authStatus: "missing",
		capabilities: ["terminal", "repo-aware", "code-edit", "bash"],
		lastSeenLabel: "auth needed",
		recommendedFor: "Open model coding candidates",
	},
	{
		id: "agent_pi",
		kind: "pi",
		name: "Pi",
		command: "pi",
		version: "0.12.4",
		status: "ready",
		authStatus: "configured",
		capabilities: ["terminal", "json-events", "rpc", "sdk", "message-queue", "session-branching", "custom-tools"],
		latencyMs: 116,
		lastSeenLabel: "ready",
		recommendedFor: "Structured events, SDK runs, and first-class queue semantics",
	},
];

export const activeRun: ActiveRun = {
	id: "run_auth_refresh",
	sessionId: "session_auth_refresh",
	title: "Fix flaky auth refresh test",
	task: "Stabilize auth refresh retry behavior and prove the fix with deterministic tests.",
	status: "running",
	worktreeLabel: "agentdeck-worktrees/run_auth_refresh",
	branchName: "agent/auth-refresh-flake",
	agentControlLabel: "Agent has control. You can jump in at any time.",
	confidence: 0.82,
	costUsd: 3.41,
	latencyLabel: "11m 42s",
	risk: "medium",
	graphNodes: [
		{ id: "task", label: "Task", subtitle: "Auth flake", status: "complete", metric: "scoped", x: 8, y: 48 },
		{ id: "router", label: "Router", subtitle: "2 candidates", status: "complete", metric: "0.4s", x: 21, y: 48 },
		{ id: "claude", label: "Claude Code", subtitle: "editing session.ts", status: "running", metric: "132ms", x: 37, y: 28 },
		{ id: "codex", label: "Codex", subtitle: "waiting verifier", status: "waiting", metric: "188ms", x: 37, y: 68 },
		{ id: "opencode", label: "OpenCode", subtitle: "candidate passed", status: "complete", metric: "94ms", x: 53, y: 68 },
		{ id: "verify", label: "Verification", subtitle: "42/44 tests", status: "running", metric: "3m", x: 68, y: 48 },
		{ id: "judge", label: "Judge", subtitle: "pending evidence", status: "waiting", metric: "hold", x: 82, y: 48 },
		{ id: "human", label: "Human Review", subtitle: "no auto-merge", status: "idle", metric: "manual", x: 94, y: 48 },
	],
	graphEdges: [
		{ id: "task-router", from: "task", to: "router", status: "complete" },
		{ id: "router-claude", from: "router", to: "claude", status: "active" },
		{ id: "router-codex", from: "router", to: "codex", status: "waiting" },
		{ id: "codex-opencode", from: "codex", to: "opencode", status: "complete" },
		{ id: "claude-verify", from: "claude", to: "verify", status: "active" },
		{ id: "opencode-verify", from: "opencode", to: "verify", status: "complete" },
		{ id: "verify-judge", from: "verify", to: "judge", status: "waiting" },
		{ id: "judge-human", from: "judge", to: "human", status: "waiting" },
	],
	timeline: [
		{
			id: "evt_1",
			title: "Worktree prepared",
			description: "Created isolated branch from main and captured base commit.",
			status: "complete",
			timeLabel: "09:12",
			source: "bridge",
		},
		{
			id: "evt_2",
			title: "Claude Code started",
			description: "Agent is inspecting auth refresh retry timing.",
			status: "running",
			timeLabel: "09:14",
			source: "agent",
		},
		{
			id: "evt_3",
			title: "Verifier running",
			description: "Targeted auth refresh test is looping for stability evidence.",
			status: "running",
			timeLabel: "09:21",
			source: "verifier",
		},
		{
			id: "evt_4",
			title: "Approval requested",
			description: "Dependency install requires human approval before continuing.",
			status: "blocked",
			timeLabel: "09:23",
			source: "worker",
		},
	],
	verification: [
		{
			id: "ver_typecheck",
			label: "Typecheck",
			command: "pnpm typecheck",
			status: "passed",
			summary: "No TypeScript errors.",
			durationLabel: "41s",
		},
		{
			id: "ver_tests",
			label: "Unit tests",
			command: "pnpm test auth-refresh.spec.ts",
			status: "warning",
			summary: "42/44 passed. Retry loop still collecting evidence.",
			durationLabel: "3m 12s",
		},
		{
			id: "ver_lint",
			label: "Lint",
			command: "pnpm lint",
			status: "warning",
			summary: "One import order warning in session test helper.",
			durationLabel: "28s",
		},
		{
			id: "ver_build",
			label: "Build",
			command: "pnpm build",
			status: "pending",
			summary: "Queued after approval decision.",
			durationLabel: "waiting",
		},
	],
	approvals: [
		{
			id: "approval_install",
			kind: "command",
			title: "Allow pnpm install?",
			description: "Agent wants to refresh lockfile metadata before running full verification.",
			risk: "medium",
			status: "pending",
			requestedBy: "Claude Code",
			createdLabel: "2m ago",
		},
		{
			id: "approval_ci",
			kind: "file",
			title: "Allow edit to CI workflow?",
			description: "Candidate patch touches .github/workflows/ci.yml and requires review.",
			risk: "high",
			status: "pending",
			requestedBy: "OpenCode",
			createdLabel: "5m ago",
		},
	],
	terminalTabs: [
		{
			id: "claude",
			label: "Claude Code",
			runId: "run_auth_refresh_claude",
			status: "running",
			lines: [
				{ id: "c1", timestamp: "09:14:02", prompt: "$", text: "claude \"Fix flaky auth refresh test\"", tone: "info" },
				{ id: "c2", timestamp: "09:14:09", text: "Reading src/auth/session.ts and auth-refresh.spec.ts", tone: "muted" },
				{ id: "c3", timestamp: "09:15:41", text: "Found retry timer race: refresh promise resolves after stale session write.", tone: "warning" },
				{ id: "c4", timestamp: "09:18:33", prompt: "$", text: "git diff -- src/auth/session.ts", tone: "info" },
				{ id: "c5", timestamp: "09:21:14", text: "Running targeted verifier: pnpm test auth-refresh.spec.ts -- --repeat=20", tone: "success" },
			],
		},
		{
			id: "codex",
			label: "Codex",
			runId: "run_auth_refresh_codex",
			status: "waiting",
			lines: [
				{ id: "x1", timestamp: "09:13:55", prompt: "$", text: "codex run --profile verifier", tone: "info" },
				{ id: "x2", timestamp: "09:14:37", text: "Waiting for Claude candidate patch before cross-check.", tone: "muted" },
			],
		},
		{
			id: "opencode",
			label: "OpenCode",
			runId: "run_auth_refresh_opencode",
			status: "passed",
			lines: [
				{ id: "o1", timestamp: "09:12:49", prompt: "$", text: "opencode run auth-refresh-flake", tone: "info" },
				{ id: "o2", timestamp: "09:20:10", text: "Candidate complete. Targeted tests passed 20/20.", tone: "success" },
			],
		},
		{
			id: "qwen",
			label: "Qwen",
			runId: "run_auth_refresh_qwen",
			status: "idle",
			lines: [{ id: "q1", timestamp: "09:10:00", text: "Auth missing. Configure before routing tasks.", tone: "warning" }],
		},
		{
			id: "pi",
			label: "Pi",
			runId: "run_auth_refresh_pi",
			status: "idle",
			lines: [{ id: "p1", timestamp: "09:10:02", text: "Ready for SDK, RPC, JSON event, or PTY mode.", tone: "success" }],
		},
		{
			id: "tests",
			label: "Tests",
			runId: "run_auth_refresh_tests",
			status: "running",
			lines: [
				{ id: "t1", timestamp: "09:21:17", prompt: "$", text: "pnpm test auth-refresh.spec.ts -- --repeat=20", tone: "info" },
				{ id: "t2", timestamp: "09:23:58", text: "pass 42/44, retrying failed seed 8871", tone: "warning" },
			],
		},
		{
			id: "system",
			label: "System",
			runId: "run_auth_refresh_system",
			status: "idle",
			lines: [{ id: "s1", timestamp: "09:11:30", text: "Metadata-only sync enabled. Raw terminal logs remain local unless approved.", tone: "muted" }],
		},
	],
};

export const queueItems: QueueItem[] = [
	{
		id: "queue_billing",
		task: "Refactor billing service",
		repo: "agentdeck",
		branch: "main",
		agent: "Claude Code",
		priority: "high",
		status: "queued",
		scheduleWindow: "Tonight 01:00-04:00 IST",
		estimate: "$6.00 / 90m",
		risk: "medium",
	},
	{
		id: "queue_api_tests",
		task: "Generate missing API tests",
		repo: "agentdeck",
		branch: "main",
		agent: "Codex",
		priority: "normal",
		status: "waiting-machine",
		scheduleWindow: "When MacBook is online",
		estimate: "$2.40 / 35m",
		risk: "low",
	},
	{
		id: "queue_tanstack",
		task: "Upgrade TanStack Query usage",
		repo: "agentdeck",
		branch: "feature/ui-data",
		agent: "Pi",
		priority: "normal",
		status: "waiting-approval",
		scheduleWindow: "Manual approval required",
		estimate: "$4.20 / 50m",
		risk: "high",
	},
];

export const scheduledJobs: ScheduledJob[] = [
	{
		id: "sched_regression",
		name: "Nightly regression run",
		naturalLanguage: "Run every weekday at 1 AM IST",
		cron: "0 1 * * 1-5",
		timezone: "Asia/Kolkata",
		nextRunLabel: "Mon 01:00",
		lastStatus: "success",
		enabled: true,
	},
	{
		id: "sched_deps",
		name: "Weekly dependency review",
		naturalLanguage: "Review outdated packages every Monday at 9 AM",
		cron: "0 9 * * 1",
		timezone: "Asia/Kolkata",
		nextRunLabel: "Mon 09:00",
		lastStatus: "never-run",
		enabled: true,
	},
	{
		id: "sched_summary",
		name: "Monday engineering summary",
		naturalLanguage: "Summarize open reports every Monday morning",
		cron: "30 8 * * 1",
		timezone: "Asia/Kolkata",
		nextRunLabel: "Mon 08:30",
		lastStatus: "failed",
		enabled: false,
	},
];

export const decisionReport: DecisionReport = {
	id: "report_auth_refresh",
	sessionId: "session_auth_refresh",
	summary: "Likely fix is a narrower session write guard plus deterministic retry timing test. Verification is still collecting repeated test evidence.",
	recommendation: "review-carefully",
	confidence: 0.82,
	agentsUsed: ["Claude Code", "Codex", "OpenCode"],
	filesChanged: 3,
	commandsRun: 7,
	humanInterventions: 1,
	costUsd: 3.41,
	latencyLabel: "11m 42s",
	candidateComparison: [
		{
			id: "candidate_a",
			agent: "OpenCode",
			status: "completed",
			score: 0.91,
			recommendation: "accept",
			verificationStatus: "passed",
			latencyLabel: "8m 18s",
			notes: "Smallest patch with repeated auth refresh test passing.",
		},
		{
			id: "candidate_b",
			agent: "Claude Code",
			status: "completed",
			score: 0.82,
			recommendation: "review-carefully",
			verificationStatus: "warning",
			latencyLabel: "11m 42s",
			notes: "Strong diagnosis, broader patch, verifier still collecting evidence.",
		},
		{
			id: "candidate_c",
			agent: "Codex",
			status: "failed",
			score: 0.28,
			recommendation: "reject",
			verificationStatus: "failed",
			latencyLabel: "4m 09s",
			notes: "Stopped after reproducing the flake but did not produce a passing patch.",
		},
	],
};

export const policyRules: PolicyRule[] = [
	{
		id: "policy_project_read",
		action: "Read approved workspace files",
		defaultDecision: "allow",
		reason: "Required for repository-aware coding.",
		risk: "low",
	},
	{
		id: "policy_install",
		action: "Install dependencies or modify lockfiles",
		defaultDecision: "approval",
		reason: "Supply-chain risk and reproducibility impact.",
		risk: "medium",
	},
	{
		id: "policy_push",
		action: "Git push, merge, deploy, or publish",
		defaultDecision: "deny",
		reason: "AgentDeck is human-controlled and never auto-merges by default.",
		risk: "critical",
	},
	{
		id: "policy_secrets",
		action: "Read or print secrets and credential files",
		defaultDecision: "approval",
		reason: "Secrets must stay local unless the user explicitly approves.",
		risk: "critical",
	},
];
